### ISSUE TITLE
Setting main class attribute in MANIFEST.MF to a class that doesnt exist (Name Obfuscation)

### ISSUE THREAD

**Issue by MOMIN5** [vimasig/Bozar#3] opened 2021-05-21 11:02 UTC
**Describe the bug**
When i try to name obfuscate, it sets the MainClass attribute to a class that doesnt exist

**To Reproduce**
use the "Alphabet" method in a jar with mainclass    
here is my config (saved in .txt for only uploading as attachement)
[bozarConfig.txt](https://github.com/vimasig/Bozar/files/6522041/bozarConfig.txt)

**Expected behavior**
sets the main variable as the obfuscated main file name

**Screenshots**
![bozer](https://user-images.githubusercontent.com/70264419/119127571-1e196f00-ba52-11eb-8b5c-a6568ffc4ab9.png)

**Bozar version**
the newest one in releases

**Additional context**
nope

**Comment by vimasig** [comment] 2021-05-21 22:18
I made a JAR like that to test this
![classes](https://i.imgur.com/CwxQfSe.png)

Renaming job is done correctly and the application is running without any issues.
![metainf](https://i.imgur.com/fIv0qSg.png)

Did you get any errors when obfuscating? Maybe class exists but cannot be written for another reason.
Does the new class count match the old one?

Also, "Dummy class" watermark is enabled in your config but I can't see that.
Look for errors in the console for that too.

Can you provide more information so I can reproduce it?

**Comment by MOMIN5** [comment] 2021-05-22 08:08
huh, I tested it in a Windows VM and it worked, maybe it's a Linux only issue?     

working on windows
![bz3](https://user-images.githubusercontent.com/70264419/119219389-f6ceaa80-bb02-11eb-8aaf-4cac84093d91.PNG)


it still didn't create a dummy class tho, here are the two errors I got (in the windows VM)     

![bz1](https://user-images.githubusercontent.com/70264419/119219346-c38c1b80-bb02-11eb-80c8-b235d5554574.PNG)
![bz2](https://user-images.githubusercontent.com/70264419/119219350-c6870c00-bb02-11eb-8084-264b6fd0478d.PNG)

**Comment by vimasig** [comment] 2021-05-22 15:35
The main issue looks like Bozar can't process all of your classes. The class count is different from the first SS.
Looks like something is wrong with CustomClassWriter (used to find classes) but I can't tell without making tests.

Try disabling shuffle so maybe you can always get the same error & result. (Shuffle can cause the unprocessable class to be randomly selected. Which is why you get different class count)

You can try excluding all classes and removing them one by one to find unprocessable classes.

Unfortunately, I can't reproduce this issue.
Can you provide a sample JAR/code which can reproduce this?

**Comment by MOMIN5** [comment] 2021-05-22 18:37
i turned shuffle off, there is no error but now there are only 3 classes and no dummy class, some classes of the jar is in kotlin tho, maybe this has to do something with the fact that the jar is an anti-debugger / anti-dumper, its a heavily modified version of 
[Falcon-forge](https://github.com/x4e/falcon-forge) with some extra disablers, I will send you the original jar later after removing all the sensitive details

**Comment by MOMIN5** [comment] 2021-06-01 15:39
here is the jar, sorry for being late btw
[myzip.zip](https://github.com/vimasig/Bozar/files/6577486/myzip.zip)

Also any idea why it doesnt include any library files in the output jar when i exclude them from obfuscating

**Comment by vimasig** [comment] 2021-06-01 19:42
Fixed. Will be released as v1.6.0 soon.

Do you want libraries to be automatically placed in the output JAR?
Or the input jar contains libraries already, but when you exclude them, they're not placed in the output JAR?

**Comment by MOMIN5** [comment] 2021-06-02 00:20
the input jar contains libraries already, but when i exclude them, they're not placed in the output JAR

**Comment by vimasig** [comment] 2021-06-02 01:57
I think it's not related to exclude. In v1.5, Bozar aborts the writing process when an exception occurs while processing classes.
This should not happen in v1.6 as the issue is fixed, and it will continue even when an exception occurs.

Let me know if it still happens

**Closed by vimasig** 2021-06-02 01:57 UTC
Labels: bug, more info requested

**Comment by MOMIN5** [comment] 2021-06-02 03:40
thanks it worked :+1:
